services:
  hping3-attacker:
    build: .
    container_name: hping3-attacker
    networks:
      custom_net:
        ipv4_address: 192.168.6.132
    environment:
      - TARGET_IP=192.168.6.131
      - TARGET_PORT=5000
      - PACKET_COUNT=1000
      - PACKET_RATE=100
    cap_add:
      - NET_RAW
    volumes:
      - ./cleanup_iptables.sh:/cleanup_iptables.sh:ro
    # Optional: uncomment to keep container running
    # stdin_open: true
    # tty: true

networks:
  custom_net:
    external: true
    name: custom_net
