version: '3.8'

services:
  flask-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: network-monitor
    hostname: network-monitor
    ports:
      - "5000:5000"
    volumes:
      - ../captures:/app/captures
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  haproxy:
    image: haproxy:2.4
    container_name: haproxy-lb
    ports:
      - "8080:8080"
    volumes:
      - ../src/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - flask-app
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  monitoring:
    driver: bridge